<a href="https://colab.research.google.com/github/busraatasoy/veri_bilimi_ve_makine_ogrenmesi_100gun_kamp/blob/main/Day_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📊 Veri Bilimine Giriş – Temel Python Kütüphaneleri


Veri bilimi çalışmalarında Python, esnek yapısı ve güçlü kütüphaneleri sayesinde en çok tercih edilen dillerden biridir. Bu alanda kullanılan temel kütüphaneler şunlardır:

* **NumPy (Numerical Python):**
  Sayısal hesaplamalar için temel kütüphanedir. Çok boyutlu diziler (array) ile çalışmayı kolaylaştırır ve matematiksel işlemleri yüksek performansla gerçekleştirir.

* **Pandas:**
  Veri analizi ve manipülasyonu için kullanılır. DataFrame yapısı sayesinde tablo şeklindeki verilerle çalışmak, filtreleme, gruplama ve dönüştürme işlemlerini pratik hale getirir.

* **Matplotlib:**
  Veri görselleştirmede kullanılan temel kütüphanedir. Grafikler, histogramlar, çizgi ve çubuk grafikler gibi görselleştirmeler oluşturmayı sağlar.

* **Seaborn:**
  Matplotlib üzerine inşa edilmiştir. Daha estetik ve istatistiksel grafikler üretmeyi kolaylaştırır. Özellikle korelasyon, dağılım ve kategorik veri görselleştirmelerinde kullanılır.

* **Scikit-learn:**
  Makine öğrenmesi için en yaygın kullanılan kütüphanelerden biridir. Sınıflandırma, regresyon, kümeleme ve model değerlendirme gibi birçok yöntemi barındırır.

📌 Bu kütüphaneler, veri biliminin farklı aşamalarında (veri işleme, analiz, görselleştirme ve modelleme) sıkça kullanılır ve öğrenme sürecinde temel yapı taşlarını oluşturur.

## 🔢 NumPy Kütüphanesine Giriş

**NumPy (Numerical Python)**, Python’da bilimsel ve sayısal hesaplamalar için geliştirilmiş en temel kütüphanelerden biridir.

**Öne çıkan özellikleri:**

- Çok boyutlu array (ndarray) yapısını sunar. Bu yapı, Python’daki listelerden çok daha hızlı ve verimlidir.
- Matematiksel fonksiyonlar, lineer cebir, istatistiksel işlemler gibi geniş fonksiyon setine sahiptir.

Veri bilimi, makine öğrenmesi ve derin öğrenme çalışmalarında temel yapı taşı olarak kullanılır.

Linkteki adresten NumPy'ın resmi websitesi ve dökümanlarına erişebilirsiniz: 👉🔗[Numpy website](https://numpy.org/)

## ➡ NumPy Nasıl Import Edilir?

NumPy genellikle kısaltması ile birlikte şu şekilde içe aktarılır:



```
import numpy as np
```
Bu satır sayesinde artık kütüphanedeki fonksiyonlara `np` kısaltmasıyla erişebiliriz.


## ➡ NumPy Kurulu Değilse Ne Yapmalı?

Google Colab ortamında NumPy önceden kurulu gelir. Ancak kendi bilgisayarınızda çalışırken NumPy yüklü değilse, aşağıdaki komutla yükleyebilirsiniz:



```
!pip install numpy
```
Ardından tekrar `import numpy as np` yazarak kullanmaya başlayabilirsiniz.


## ➡ **NumPy Dizileri**

NumPy’nin en temel veri yapısı **ndarray (n-dimensional array)** yani çok boyutlu dizilerdir.

**Özellikleri:**

- Python’daki listelere benzer, ancak **daha hızlı ve daha verimlidir**.
- Tek boyutlu (vektör), iki boyutlu (matris) veya daha yüksek boyutlu diziler oluşturulabilir.
- Tüm elemanları aynı tipte (int, float, vb.) saklar.
- Sayısal işlemler için optimize edilmiştir.

Linkten ayrıntılı olarak yapılarını inceleyebilirsiniz: 👉🔗[Numpy dizileri(ndarray)](https://jalammar.github.io/visual-numpy/)

In [ ]:
# Kütüphaneyi yükleyelim:

import numpy as np

In [ ]:
# Liste oluşturalım:

my_list = [10,20,30,40]

In [ ]:
# Kontrol edelim:

type(my_list)

list

In [ ]:
# Dizi oluşturalım:

np.array(my_list)

array([10, 20, 30, 40])

In [ ]:
# Sonucu değişkene atayalım:

my_numpy_array = np.array(my_list)

In [ ]:
# Kontrol edelim:

type(my_numpy_array )

numpy.ndarray

In [ ]:
# max değeri bulmak:

my_numpy_array.max()

np.int64(40)

In [ ]:
# min değeri bulmak:

my_numpy_array.min()

np.int64(10)

In [ ]:
# İçinde 1 geçen rastgele değerler üretmek:

np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# İçinde 0 geçen rastgele değerler üretmek:

np.zeros(5)


array([0., 0., 0., 0., 0.])

In [ ]:
# Rastgele değerler üretmek:
# 0-1 arasında

np.random.random(5)

array([0.46931202, 0.32571618, 0.15438297, 0.33910397, 0.72634733])

## ➡ **Dizi Aritmetiği**

**NumPy Dizilerinde Aritmetik İşlemler**

NumPy dizileri üzerinde toplama, çıkarma, çarpma, bölme gibi matematiksel işlemler çok kolay yapılır.

Normal Python listelerinde döngü kullanmamız gerekirken, NumPy dizileri vektörleştirilmiş yapıları sayesinde işlemleri **eleman bazlı** (element-wise) uygular.

**🎯 Öne Çıkan Noktalar**

- İşlemler tek tek döngü yazmadan **dizinin tüm elemanlarına uygulanır.**
- İki dizinin şekilleri (shape) uyumluysa, işlem eleman bazında yapılır.
- Bu özellik NumPy’yi veri analizi ve bilimsel hesaplamalarda çok hızlı hale getirir.

In [ ]:
# Liste oluştur

my_list = [1,2]

In [ ]:
# Liste oluştur

my_list2 = [2,3]

In [ ]:
# Listeleri topla
# Yanyana yazar

my_list + my_list2

[1, 2, 2, 3]

In [ ]:
# dizi oluştur

arr1 = np.array(my_list)

In [ ]:
# dizi oluştur

arr2 = np.array(my_list2)

In [ ]:
# Dizileri toplama işlemi
# Karşılıklı indexler toplanır

arr1 + arr2

array([3, 5])

In [ ]:
# Çarpma işlemi

arr1 * arr2

array([2, 6])

In [ ]:
# Çıkarma işlemi

arr1 - arr2

array([-1, -1])

In [ ]:
# Bölme işlemi

arr1 / arr2

array([0.5       , 0.66666667])

In [ ]:
# Sabitle çarpma

arr1 * 5

array([ 5, 10])

In [ ]:
#  Yeni bir dizi tanımlayalım

other_arr = np.array([10,20,30,40,50])

In [ ]:
# Min bulma:

other_arr.min()

np.int64(10)

In [ ]:
# Otomatik toplam alma:

other_arr.sum()

np.int64(150)

In [ ]:
# Indexler eşleşmediğinde toplanır mı?

# other_arr + arr1

Hayır. Kod çalıştırıldığında `ValueError` hatası alındı. Eleman sayıları eşit olmadığından toplama yapılamayacağı bilgisini alırız.

Daha detaylı incelemek için NumPy dökümanındaki **broadcasting** bölümünü inceleyebilirsiniz. 🔗[Link](https://numpy.org/doc/stable/user/basics.broadcasting.html)

## ➡ **Index İşlemleri**

NumPy dizilerinde indexleme(indexing), dizinin belirli bir elemanına veya alt dizisine erişmek için kullanılır.

Python listelerine benzer şekilde çalışır ama çok daha güçlüdür.

**range()** → Python fonksiyonu, liste benzeri bir yapı döner, sadece tam sayılar üretir.

In [ ]:
 # listelerde range işlemi

 list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

**np.arange()**→ NumPy fonksiyonu, NumPy dizisi döner, hem tam sayı hem de ondalık sayı üretebilir.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 2'şerli sayarak aralık oluşturma

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Dizi oluşturalım

np_array = np.arange(0,10)

np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 1. elemanı indexleme ile alalım

np_array[0]

np.int64(0)

In [ ]:
# Son elemana indexing ile ulaşalım

np_array[-1]

np.int64(9)

In [ ]:
# Slicing işlemi

np_array[1:4:]

array([1, 2, 3])

In [ ]:
# Tersten yazdıralım

np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
# Slicing işlemi ile dizi oluşturma
# start:2, stop:6, step size:2

np_array[2:6:2]

array([2, 4])

**NumPy Rastgele Sayılar: random(), randn(), randint()**

NumPy’nin np.random modülü, rastgele sayı üretmek için çok güçlü fonksiyonlar içerir.

En sık kullanılan üç fonksiyon: `random()`, `randn()`, `randint()`

**1. np.random.random() işlemi:**

- 0 ile 1 arasında uniform (eşit olasılıklı) rastgele sayı üretir.

- Tek bir sayı ya da bir dizi üretmek mümkündür.

In [ ]:
# Tek sayı üretme

np.random.random()

0.9809730433074564

In [ ]:
# Bir dizi üretme

np.random.random(5)

array([0.18576318, 0.42411334, 0.99382442, 0.54023742, 0.14971803])

**2. np.random.randn()**

- Standart normal dağılımdan (ortalama=0, std=1) rastgele sayı üretir.

- Negatif ve pozitif değerler üretir.

In [ ]:
# Random(rastgele) işlemi

np.random.randn(4)

array([-0.98952959,  0.73895293,  0.64043801, -0.25237243])

In [ ]:
# Random(rastgele) işlemi
# Matris oluşturur

np.random.randn(4,4)

array([[ 0.51409316, -0.2726832 , -1.44468467,  0.26449718],
       [-0.23634464,  0.48976679,  0.30872737,  1.18936641],
       [-1.48079503, -0.60953183,  0.20663653,  1.7275429 ],
       [-0.36332097,  1.41851545, -1.76837553,  0.98606494]])

**3. np.random.randint()**

- Belirtilen aralıkta tam sayılar üretir.

- Bitiş değeri dahil değildir.

In [ ]:
np.random.randint(1,300,5)

array([254, 107,  92, 265,   1])

## ➡ **Matrixlere Giriş**

**NumPy matrix Sınıfına Giriş**

NumPy’de matrix sınıfı, özel olarak 2 boyutlu matrisleri temsil etmek için geliştirilmiş bir yapıdır.

Aslında ndarray’in bir alt sınıfıdır, ama bazı davranışları farklıdır.

Matrixlerden bahsederken 3 sıralı, 2 sütunlu matrisden oluşur şeklinde bahsedilir.

Yani; row & column şeklinde belirtilir.

**1. Matrix Oluşturma:**

In [ ]:
# kütüphaneyi yükle
import numpy as np

#matrix oluştur
my_matrix = [[5,10],[15,20]]

In [ ]:
#1. elemana erişme

my_matrix[0]

[5, 10]

In [ ]:
#2.elemana erişme

my_matrix[1]

[15, 20]

In [ ]:
#1.elemanın 2. verisine erişme

my_matrix[0][1]

10

In [ ]:
# numpy ile matrix oluşturma:

numpy_matrix = np.array([[5,10],[15,20]])

In [ ]:
# matrix okuyalım

numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [ ]:
# 1. satır & 0. sütuna erişelim

numpy_matrix[1,0]

np.int64(15)

In [ ]:
# Otomatik toplam alma

numpy_matrix.sum()

np.int64(50)

In [ ]:
# ones kullanarak matrix oluşturma

np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# zeros kullanarak matrix oluşturma

np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# random ile rastegele sayı üreten matrix oluşturma

np.random.random((3,2))

array([[0.8818819 , 0.62542281],
       [0.67057789, 0.02166488],
       [0.13883089, 0.50274945]])

## ➡ **Matrix Aritmetiği**

NumPy’de matrix sınıfı, 2 boyutlu matrisler için özel olarak geliştirilmiştir.

Aritmetik işlemler `(+, -, *) `normal matematik kurallarına uygun çalışır.

In [ ]:
#1. matrix:

first_arr = np.array([[10,20],[30,40]])

In [ ]:
#2. matrix:

second_arr = np.array([[5,15],[25,35]])

In [ ]:
#Toplama işlemi

first_arr + second_arr

array([[15, 35],
       [55, 75]])

In [ ]:
# Çıkarma işlemi

first_arr - second_arr

array([[5, 5],
       [5, 5]])

In [ ]:
# Çarpma işlemi

first_arr * second_arr

array([[  50,  300],
       [ 750, 1400]])

In [ ]:
# Skaler ile çarpımı(tek sayı ile)

first_arr * 5

array([[ 50, 100],
       [150, 200]])

In [ ]:
# Başka bir matrix oluşturalım

third_arr = np.array([[50,60]])

In [ ]:
# Tüm matrixleri yazdıralım

print("1. matrix:\n", first_arr)


print("2. matrix:\n", second_arr)

print("3. matrix:\n", third_arr)

1. matrix:
 [[10 20]
 [30 40]]
2. matrix:
 [[ 5 15]
 [25 35]]
3. matrix:
 [[50 60]]


In [ ]:
# Farklı matrix boyutları ile toplama yapalım

first_arr + third_arr

array([[ 60,  80],
       [ 80, 100]])

Görüldüğü gibi, **first_arr (2,2) boyutunda, third_arr ise (1,2) boyutunda.**

NumPy boyutları karşılaştırır:

- (2,2)

- (1,2)

Küçük boyutlu matris, **broadcasting kuralı**na göre genişletilir.

Yani third_arr, satır bazında kopyalanarak şu hale gelir:



```
[[50 60]
 [50 60]]
```
Sonra toplama işlemi element bazlı yapılır:



```
[[10+50, 20+60],
 [30+50, 40+60]]
= [[60, 80],
   [80, 100]]
```


**Broadcasting Her Boyuta Uygulanabilir mi?**

**Cevap:** Hayır, broadcasting her boyuta otomatik olarak uygulanamaz.

**Broadcasting Kuralları:**

- NumPy’de iki dizinin toplama, çıkarma veya diğer element-wise işlemlerinde **broadcasting yapılabilmesi için**:

- Dizilerin son boyutlarından başlayarak boyut sayıları **eşit** olmalı veya **biri 1** olmalı.

- Boyutlar yukarıdan aşağıya karşılaştırılır ve eğer herhangi bir boyutta bu koşul sağlanmazsa `ValueError` alınır.

In [ ]:
# fourth_arr tanımlayalım:


fourth_arr = np.array([[10,20,30,40,50]])

In [ ]:
# İşlemi yapalım

# first_arr + fourth_arr

Kod çalıştırıldığında `ValueError:` operands could not be broadcast together with shapes (2,2) (1,5)

Görüldüğü gibi, boyutlar uyumsuz, son boyutlar 2 ve 6, eşleşmiyor ve biri 1 değil → **broadcasting mümkün değil**.

In [ ]:
# Çarpma işlemi deneyelim

first_arr * 2

array([[20, 40],
       [60, 80]])

In [ ]:
# Bölme işlemi yapalım

first_arr / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [ ]:
# third_arr yeniden tanımlayalım

third_arr = np.array([[10],[20]])

third_arr

array([[10],
       [20]])

In [ ]:
# array şekline bakalım

third_arr.shape

(2, 1)

In [ ]:
# first_arr şekline bakalım

first_arr.shape

(2, 2)

In [ ]:
# Toplama işlemi yapalım

third_arr + first_arr

array([[20, 30],
       [50, 60]])

Üst değerler üstlerler, alt değerler altlar ile toplanır.

## ➡ **Matrix Çarpımları**

**Matris çarpımı(matrix multiplication)**, iki matrisin elemanlarının aynı konumdaki değerlerle değil, **satır ve sütun kombinasyonlarıyla çarpılıp toplanmasıdır.**

Bu işlem element-wise **toplama/çarpma** işlemlerinden **farklıdır.**

Matrix işlemleri özellikle görüntü işleme alanında çok fazla kullanılmaktadır.

**1. Element-wise (Eleman Bazlı) Çarpma**

Aynı boyutlardaki iki matrisin elemanları birebir çarpılır:

In [ ]:
first_arr

array([[10, 20],
       [30, 40]])

In [ ]:
second_arr

array([[ 5, 15],
       [25, 35]])

In [ ]:
# first_arr ve second_arr ile çarpma işlemi yapalım

first_arr * second_arr

array([[  50,  300],
       [ 750, 1400]])

Satır ve sütun değerleri karşılıklı olarak çarpılır.

**2. Gerçek Matris Çarpımı (Dot Product)**

Matematikteki klasik matris çarpımıdır.

Kural: **Birinci matrisin sütun sayısı, ikinci matrisin satır sayısına eşit** olmalıdır.




```
print(np.dot(A, B))
# veya A @ B şeklinde de yazılabilir

```



In [ ]:
# Yeni matrix tanımlayalım

first_matrix = np.array([[10,20,30]])

first_matrix

array([[10, 20, 30]])

In [ ]:
# Matrix şeklini kontrol edelim

first_matrix.shape

(1, 3)

In [ ]:
# İkinci matrix tanımlayalım

second_matrix = np.array([[2,3],[2,3],[2,3]])

second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [ ]:
# Matrix şeklini kontrol edelim

second_matrix.shape

(3, 2)

In [ ]:
# Element bazlı çarpımda hata verir
# Satır-sütun uyuşmazlığı

# first_matrix * second_matrix

In [ ]:
# Dot product ile çarpım işlemi

result_matrix = first_matrix.dot(second_matrix)

result_matrix

array([[120, 180]])

In [ ]:
#Şeklini kontrol edelim

result_matrix.shape

(1, 2)

In [ ]:
# dot yerine @ ile kullanımı ile çarpımı

result_matrix2 = first_matrix @ second_matrix

result_matrix2

array([[120, 180]])

## ➡ **NumPy Gerçek Örnekler**

In [ ]:
import numpy as np

new_array = np.random.randint(1,100,20)

new_array

array([76, 42, 14, 86, 90, 55, 15, 36, 13,  9, 38,  5, 59, 72, 94, 50, 34,
       47, 21, 85])

In [ ]:
# 25'ten büyük sayıları alalım
# Sonuç boolen

new_array > 25

array([ True,  True, False,  True,  True,  True, False,  True, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True])

In [ ]:
# 25'ten büyük sayıları alalım
# boolen döndürmemesi için listeye çeviririz

new_array [new_array > 25]

array([76, 42, 86, 90, 55, 36, 38, 59, 72, 94, 50, 34, 47, 85])

In [ ]:
# 25'ten küçük sayıları alalım
# boolen döndürmemesi için listeye çeviririz

new_array [new_array < 25]


array([14, 15, 13,  9,  5, 21])

**Transpose ve Reshape İşlemleri**

Transpose ile tersini alma işlemi yapabiliriz.

Reshape ile verileri değiştirmeden dizilerin şekline yeni bir boyut verebiliriz.

In [ ]:
# yeni matrix tanımlayalım

matrix_array = np.array([[10,20],[20,30],[30,40] ])

matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [ ]:
# Şeklini kontrol edelim

matrix_array.shape

(3, 2)

In [ ]:
# Tranpose işlemi yapalım

matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [ ]:
# Tranpose işlemi yapalım

matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [ ]:
# Rastgele dizi oluşturalım

random_array = np.random.random((6,1))

random_array

array([[0.3631353 ],
       [0.41124704],
       [0.79899427],
       [0.43494426],
       [0.57708768],
       [0.3502794 ]])

In [ ]:
# Şeklini kontrol edelim

random_array.shape

(6, 1)

In [ ]:
# Farklı bir şekil boyutu verelim

random_array.reshape(2,3)

array([[0.3631353 , 0.41124704, 0.79899427],
       [0.43494426, 0.57708768, 0.3502794 ]])

In [ ]:
# Farklı bir şekil boyutu verelim

random_array.reshape(3,2)

array([[0.3631353 , 0.41124704],
       [0.79899427, 0.43494426],
       [0.57708768, 0.3502794 ]])

In [ ]:
# Z-Score Hesaplama
# Outlier değerler var.

data = np.array([10,12,13,15,18,25,100,105])
data

array([ 10,  12,  13,  15,  18,  25, 100, 105])

In [ ]:
# Ortalama hesaplama

mean = np.mean(data)

mean

np.float64(37.25)

In [ ]:
# Veri toplamı

data.sum()

np.int64(298)

In [ ]:
# Manuel ortalama(veri toplamı/veri sayısı)

data.sum() / len(data)

np.float64(37.25)

In [ ]:
# standart sapma hesaplama

std = np.std(data)

std

np.float64(37.9333296719389)

In [ ]:
# Z Score = (Veri- Ortalama) / Standart sapma

z_score = (data - mean) / std

z_score

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [ ]:
# z score 1'den büyük olanları bulalım
# Boolen formunda gelir

z_score > 1

array([False, False, False, False, False, False,  True,  True])

In [ ]:
# z score 1'den büyük olanlar değerler hangileri?

z_score[z_score > 1]

array([1.65421809, 1.78602829])

In [ ]:
# z score 1'den büyük olanlar veriler hangileri?
# Outlier değerlerdir.

data[z_score > 1]

array([100, 105])

In [ ]:
# math equations(matematik denklemleri)

# 2x + 3y = 8 and 5x +7y =19

In [ ]:
# coefficient olanları matrix oluşturalım.( Denklem katsayıları)

A = np.array([[2,3],[5,7]])

A

array([[2, 3],
       [5, 7]])

In [ ]:
# Constant olanları matrix oluşturalım.(Sabit sayılar)

B = np.array([8,19])

B

array([ 8, 19])

In [ ]:
# Denklemi çözelim
# linalg yani lineeralgebra fonksiyonu kullanılır.

solution = np.linalg.solve(A,B)

solution

array([1., 2.])

Burada cevap x = 1, y = 2 olarak bulundu. Denklemde yerine koyduğumuzda eşitlik sağlanır.